export const clipboardTextUpdatedChannel = 'clipboard-text-updated'
export const openBrowserWindowChannel = 'open-browser-window'
export const openFileDialogChannel = 'open-file-dialog'
export const getLogfilePathChannel = 'get-logfile-path'
export const readGameLogsChannel = 'read-game-logs'
